# This is a basic workflow to help you get started with Actions

name: Build ACPCore

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, Githubactions ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - run: |
          echo "./ACPCore/Assets/Plugins.meta" > metaList
          find ./ACPCore/Assets/Plugins/ -name \*.meta >> metaList
          find ./ACPCore/Assets/Plugins/Android/ -name \*.meta >> metaList
          find ./ACPCore/Assets/Plugins/iOS/ -name \*.meta >> metaList

      - run: mkdir tmp_folder

      - name: create-unitypackage
        uses: pCYSl5EDgo/create-unitypackage@v1
        with:
          # Output unitypackage file path
          package-path: './bin/build_temp/ACPCore.unitypackage'
          include-files: metaList
          project-folder: .
